spring:
  datasource:
    username: root
    password: mysql
    # serverTimezone=UTC：MySQL 8+以上使用
    url: jdbc:mysql://192.168.56.101:3306/oauth_as_rs?useUnicode=ture&characterEncoding=UTF-8&serverTimezone=UTC
    # mysql 8+以上使用
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081